definitions:
  internal_application_demo.DemoResponse:
    properties:
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /demo:
    get:
      description: Check system status
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_application_demo.DemoResponse'
      summary: Demo check
      tags:
      - Health
  /health:
    get:
      description: Check system status
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - Health
swagger: "2.0"
